language: node_js
node_js:
  - lts/*
install:
#  - yarn install
  - npm install -D vuepress
script:
  #- yarn docs:build
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: study
